name: pull request
on: 
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

    - name: set repo name
      shell: bash
      run: | 
        pwd
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV    

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download operator sdk
      shell: bash
      env:
        RELEASE_VERSION: v1.3.0
      run: | 
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
        chmod +x operator-sdk_linux_amd64
        mkdir ${HOME}/bin
        mv operator-sdk_linux_amd64 ${HOME}/bin/operator-sdk
        echo "${HOME}/bin" >> $GITHUB_PATH 

    - name: build code
      shell: bash
      run:  make VERSION=latest
      
    - name: build bundle
      shell: bash
      run: make bundle IMG=${{ secrets.STAKATER_NEXUS_PROD_REGISTRY }}/${{ github.repository }}:0.0.1 VERSION=0.0.1 DEFAULT_CHANNEL=alpha

    - name: verify bundle
      shell: bash
      run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub

    - name: build chart
      shell: bash
      run: make helmchart VERSION=0.0.1 IMG=${{ secrets.STAKATER_NEXUS_PROD_REGISTRY }}/${{ github.repository }}:0.0.1
   
    - name: Upload helm chart from build job
      uses: actions/upload-artifact@v2
      with:
        name: helm
        path: ./charts/
    
  release-helm-chart:
    name: Helm Chart Release      
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:

      - name: set repo name
        shell: bash
        run: | 
          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2       

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com "

      - name: Download helm chart from build job
        uses: actions/download-artifact@v2
        with:
          name: helm
      # Setting up helm binary
      - uses: azure/setup-helm@v1 
 
      # Publish helm chart to nexus
      - name: Publish Helm chart
        run: |
          helm package ./charts/namespace-configuration-operator --destination ./packaged-chart
          curl -u ${{ secrets.STAKATER_NEXUS_PROD_HELM_USERNAME }}:${{ secrets.STAKATER_NEXUS_PROD_HELM_PASSWORD }} ${{ secrets.STAKATER_NEXUS_PROD_HELM_REGISTRY }} --upload-file ./packaged-chart/*.tgz
          rm -rf ./packaged-chart